// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXihd0krEncSqVxvmKTyWkTaK4PyHaSXg',
    appId: '1:128155610142:web:847ff04c90cd709b87520f',
    messagingSenderId: '128155610142',
    projectId: 'proyecto1-b59eb',
    authDomain: 'proyecto1-b59eb.firebaseapp.com',
    databaseURL: 'https://proyecto1-b59eb-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-b59eb.appspot.com',
    measurementId: 'G-WFEDMLJGJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6wBNBxpHltn4_UIFuuR22Qu9prSTOw0',
    appId: '1:128155610142:android:eb979eb08e284d6e87520f',
    messagingSenderId: '128155610142',
    projectId: 'proyecto1-b59eb',
    databaseURL: 'https://proyecto1-b59eb-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-b59eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiEH1_4OOYdZacRvJnkOHsMLmIKpysc0',
    appId: '1:128155610142:ios:b2c3e619bfb2528487520f',
    messagingSenderId: '128155610142',
    projectId: 'proyecto1-b59eb',
    databaseURL: 'https://proyecto1-b59eb-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-b59eb.appspot.com',
    iosClientId: '128155610142-nlli3o93n3g2nnnb72anr7sh69cdabh9.apps.googleusercontent.com',
    iosBundleId: 'com.ucundinamarca.pruebauno',
  );
}
